 name: linting

 on: push

 jobs:
  add_numbers:
    runs-on: ubuntu-latest
    steps:
      - name: Add two numbers
        run: |
          num1=5
          num2=7
          sum=$((num1 + num2))
          echo "The sum of $num1 and $num2 is $sum". 
